(() => {
  "use strict";
  const $ = (s, root = document) => root.querySelector(s);
  const esc = (v = "") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const icon = (name) => {
    const paths = {lock:'<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',plus:'<path d="M12 5v14M5 12h14"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',send:'<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',back:'<path d="m15 18-6-6 6-6"/>',check:'<path d="m5 12 4 4L19 6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>'};
    return `<span class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${paths[name] || paths.lock}</svg></span>`;
  };
  const enc = new TextEncoder(), dec = new TextDecoder();
  const b64 = b => btoa(String.fromCharCode(...new Uint8Array(b)));
  const unb64 = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));
  const initials = n => n.split(/\s+/).map(x => x[0]).slice(0,2).join("").toUpperCase();
  const nowText = d => new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit"}).format(new Date(d));
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;

  const seedContacts = [
    {id:"demo-aylin",email:"aylin@example.com",display_name:"Aylin Demir",status:"Güvenlik numarası doğrulandı",verified:true,color:"#6c63ff",public_key:"demo-aylin-key"},
    {id:"demo-mert",email:"mert@example.com",display_name:"Mert Kaya",status:"Uçtan uca şifreli",verified:false,color:"#ef6f6c",public_key:"demo-mert-key"},
    {id:"demo-ekip",email:"ekip@example.com",display_name:"Ürün Ekibi",status:"Bugün aktif",verified:true,color:"#0da98d",public_key:"demo-ekip-key"}
  ];
  const seedMessages = {
    "demo-aylin":[
      {id:"m1",plaintext:"Güvenlik numarasını karşılaştırdım, ikimizde de aynı görünüyor.",mine:false,created_at:Date.now()-720000,status:"read",ciphertext:"dGVzdC1jaXBoZXJ0ZXh0LWJsb2I=",iv:"dGVzdC1pdi0xMjM0",digest:"5e884898da28047151d0e56f8dc62927"},
      {id:"m2",plaintext:"Harika. Bundan sonraki mesajlar yalnızca cihazlarımızda okunabilir.",mine:true,created_at:Date.now()-640000,status:"read",ciphertext:"YWVzLTI1Ni1nY20tZW5jcnlwdGVk",iv:"cmFuZG9tLW5vbmNl",digest:"7c222fb2927d828af22f592134e89324"}
    ]
  };
  const state = {step:"email",authMode:"login",email:"",session:null,profile:null,contacts:[],requests:[],blocked:[],messages:{},active:null,client:null,channel:null,demo:false,keyPair:null};
  const config = window.CIPHERCHAT_CONFIG || {};
  const configured = /^https:\/\/.+\.supabase\.co$/.test(config.supabaseUrl || "") && (config.supabaseAnonKey || "").length > 30;
  if (configured && window.supabase) state.client = window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});

  function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2600)}
  function render(){ if(!state.session && !state.demo) renderAuth(); else renderWorkspace(); }
  function authShell(content){$("#app").innerHTML=`<section class="auth-card"><div class="brand"><span class="brand-mark">${icon("lock")}</span><span>BeChat</span><span class="supabase-state ${configured?'online':''}">${configured?'● Supabase hazır':'○ Demo modu'}</span></div>${content}<div class="trust-row"><span><i class="dot"></i>AES-256-GCM</span><span><i class="dot"></i>P-256 ECDH</span><span><i class="dot"></i>Açık anahtar mimarisi</span></div>${!configured?'<div class="demo-note">Supabase bilgileri henüz eklenmemiş. Arayüzü hemen deneyebilir veya <b>supabase-config.js</b> dosyasını doldurarak gerçek e-posta doğrulamasını açabilirsiniz.</div>':''}</section>`}
  function renderAuth(){
    if(state.step==="email") {const signup=state.authMode==="signup";authShell(`<div class="auth-tabs" role="tablist"><button type="button" class="auth-tab ${!signup?'active':''}" data-mode="login">Giriş yap</button><button type="button" class="auth-tab ${signup?'active':''}" data-mode="signup">Kayıt ol</button></div><div class="eyebrow">${signup?'Yeni güvenli hesap':'Tekrar hoş geldiniz'}</div><h1>${signup?'Hesabınızı oluşturun.':'Konuşmanıza devam edin.'}</h1><p class="lead">${signup?'E-posta ve parolanızla hesabınızı oluşturun. Şifreleme anahtarınız bu tarayıcıda üretilecek.':'Kayıt olurken kullandığınız e-posta ve parolayla giriş yapın.'}</p><form id="emailForm">${signup?'<div class="field"><label>Görünen ad</label><input id="displayName" autocomplete="name" placeholder="Adınız" minlength="2" required></div>':''}<div class="field"><label>E-posta adresi</label><input id="email" type="email" autocomplete="email" placeholder="siz@ornek.com" required></div><div class="field"><label>Parola</label><input id="password" type="password" autocomplete="${signup?'new-password':'current-password'}" placeholder="En az 8 karakter" minlength="8" required></div><button class="btn block" type="submit">${signup?'Güvenli hesap oluştur':'Giriş yap'}</button>${!configured?'<button class="btn ghost block" type="button" id="demoBtn">Demo prototipi aç</button>':''}</form>`)}
    bindAuth();
  }
  function bindAuth(){
    document.querySelectorAll("[data-mode]").forEach(btn=>btn.addEventListener("click",()=>{state.authMode=btn.dataset.mode;render()}));
    $("#emailForm")?.addEventListener("submit", async e=>{e.preventDefault();state.email=$("#email").value.trim().toLowerCase();if(!state.client)return toast("Önce Supabase bağlantı bilgilerini ekleyin veya demo modunu açın");const password=$("#password").value;try{if(state.authMode==="signup"){const displayName=$("#displayName").value.trim();const {data,error}=await state.client.auth.signUp({email:state.email,password,options:{data:{display_name:displayName}}});if(error)throw error;if(!data.session){state.authMode="login";render();return toast("Kayıt tamamlandı. E-postanızı onayladıktan sonra giriş yapın.")}state.session=data.session}else{const {data,error}=await state.client.auth.signInWithPassword({email:state.email,password});if(error)throw error;state.session=data.session}await bootstrapReal()}catch(err){const msg=/invalid login credentials/i.test(err.message||"")?"E-posta veya parola hatalı":/user already registered/i.test(err.message||"")?"Bu e-posta zaten kayıtlı":err.message;toast((state.authMode==="signup"?"Kayıt olunamadı: ":"Giriş yapılamadı: ")+msg)}});
    $("#demoBtn")?.addEventListener("click",()=>{state.demo=true;state.profile={id:"demo-me",email:"deniz@example.com",display_name:"Deniz",status:"Güvenli bağlantı aktif"};state.contacts=structuredClone(seedContacts);state.messages=structuredClone(seedMessages);render()});
  }
  async function makeKeys(userId){const kp=await crypto.subtle.generateKey({name:"ECDH",namedCurve:"P-256"},true,["deriveKey","deriveBits"]);const pub=b64(await crypto.subtle.exportKey("spki",kp.publicKey));const priv=b64(await crypto.subtle.exportKey("pkcs8",kp.privateKey));localStorage.setItem(`cipherchat.keys.${userId}`,JSON.stringify({pub,priv}));state.keyPair=kp;return pub}
  async function loadKeys(userId,expectedPublicKey){const storageKey=`cipherchat.keys.${userId}`;let saved=JSON.parse(localStorage.getItem(storageKey)||"null");if(!saved){const legacy=JSON.parse(localStorage.getItem("cipherchat.keys")||"null");if(legacy&&(!expectedPublicKey||legacy.pub===expectedPublicKey)){saved=legacy;localStorage.setItem(storageKey,JSON.stringify(legacy));localStorage.removeItem("cipherchat.keys")}}if(!saved)return makeKeys(userId);try{state.keyPair={publicKey:await crypto.subtle.importKey("spki",unb64(saved.pub),{name:"ECDH",namedCurve:"P-256"},true,[]),privateKey:await crypto.subtle.importKey("pkcs8",unb64(saved.priv),{name:"ECDH",namedCurve:"P-256"},true,["deriveKey","deriveBits"])};return saved.pub}catch{return makeKeys(userId)}}
  async function bootstrapReal(){
    const user=state.session.user;
    let {data:profile}=await state.client.from("profiles").select("*").eq("id",user.id).maybeSingle();
    const pub=await loadKeys(user.id,profile?.public_key);
    if(!profile){const profileEmail=(state.email||user.email||"").toLowerCase();if(!profileEmail){await state.client.auth.signOut();state.session=null;return render()}const name=user.user_metadata?.display_name||profileEmail.split("@")[0]||"BeChat Kullanıcısı";const row={id:user.id,email:profileEmail,display_name:name,status:"Uçtan uca şifreli",public_key:pub};const {data,error}=await state.client.from("profiles").upsert(row).select().single();if(error)return toast("Profil oluşturulamadı: "+error.message);profile=data}
    else if(profile.public_key!==pub){const {data,error}=await state.client.from("profiles").update({public_key:pub}).eq("id",user.id).select().single();if(error)return toast("Şifreleme anahtarı eşitlenemedi: "+error.message);profile=data}
    state.profile=profile;await loadContacts();render();subscribe();
  }
  function decorateContact(profile, verified=false){return {...profile,verified,color:`hsl(${Math.abs(hash(profile.id))%360} 60% 48%)`}}
  async function fetchProfile(id,addToContacts=false){const existing=state.contacts.find(x=>x.id===id)||state.requests.find(x=>x.id===id);if(existing)return existing;const {data,error}=await state.client.from("profiles").select("*").eq("id",id).maybeSingle();if(error||!data)return null;const contact=decorateContact(data);if(addToContacts)state.contacts.push(contact);return contact}
  async function loadContacts(){
    const {data,error}=await state.client.from("contacts").select("verified, contact:profiles!contacts_contact_id_fkey(*)").eq("owner_id",state.profile.id);if(error){toast(error.message);return}
    state.contacts=(data||[]).map(x=>decorateContact(x.contact,x.verified));state.requests=[];state.messages={};
    const {data:blockedRows}=await state.client.from("blocked_users").select("blocked_id").eq("owner_id",state.profile.id);state.blocked=(blockedRows||[]).map(x=>x.blocked_id);
    const {data:msgs,error:messageError}=await state.client.from("messages").select("*").or(`sender_id.eq.${state.profile.id},recipient_id.eq.${state.profile.id}`).order("created_at");if(messageError){toast("Mesajlar yüklenemedi: "+messageError.message);return}
    for(const m of msgs||[]){const cid=m.sender_id===state.profile.id?m.recipient_id:m.sender_id;if(state.blocked.includes(cid))continue;const accepted=state.contacts.some(x=>x.id===cid);const c=await fetchProfile(cid,accepted);if(!c)continue;m.mine=m.sender_id===state.profile.id;m.plaintext=await decryptWithFreshKey(m,c).catch(()=>"🔒 Bu mesaj eski veya kayıp bir anahtarla şifrelenmiş");(state.messages[cid]??=[]).push(m);if(!m.mine&&!accepted&&!state.requests.some(x=>x.id===cid))state.requests.push(c)}
  }
  function hash(s){let h=0;for(const c of s)h=((h<<5)-h)+c.charCodeAt(0);return h}
  async function sharedKey(contact){if(state.demo)return null;const peer=await crypto.subtle.importKey("spki",unb64(contact.public_key),{name:"ECDH",namedCurve:"P-256"},false,[]);return crypto.subtle.deriveKey({name:"ECDH",public:peer},state.keyPair.privateKey,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
  async function encryptMessage(text,contact){const key=await sharedKey(contact),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(text)),digest=await crypto.subtle.digest("SHA-256",cipher);return{ciphertext:b64(cipher),iv:b64(iv),digest:b64(digest)}}
  async function decryptMessage(m,contact){const key=await sharedKey(contact),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(m.iv)},key,unb64(m.ciphertext));return dec.decode(plain)}
  async function decryptWithFreshKey(m,contact){try{return await decryptMessage(m,contact)}catch{const {data}=await state.client.from("profiles").select("public_key").eq("id",contact.id).maybeSingle();if(data?.public_key&&data.public_key!==contact.public_key){contact.public_key=data.public_key;return decryptMessage(m,contact)}throw new Error("message_key_unavailable")}}
  async function receiveRealtimeMessage(m){
    if((state.messages[m.sender_id]||[]).some(x=>x.id===m.id))return;
    if(state.blocked.includes(m.sender_id))return;const accepted=state.contacts.some(x=>x.id===m.sender_id),c=await fetchProfile(m.sender_id,accepted);if(!c)return toast("Yeni mesaj geldi ancak gönderen profili yüklenemedi");
    m.mine=false;m.plaintext=await decryptWithFreshKey(m,c).catch(()=>"🔒 Bu mesaj eski veya kayıp bir anahtarla şifrelenmiş");(state.messages[c.id]??=[]).push(m);
    if(!accepted&&!state.requests.some(x=>x.id===c.id))state.requests.unshift(c);render();setTimeout(()=>$("#messages")?.scrollTo(0,999999),0);toast(accepted?`${c.display_name} yeni mesaj gönderdi`:`${c.display_name} bir mesaj isteği gönderdi`)
  }
  function subscribe(){
    state.channel?.unsubscribe();
    state.channel=state.client.channel(`messages-${state.profile.id}`)
      .on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`recipient_id=eq.${state.profile.id}`},p=>receiveRealtimeMessage(p.new))
      .subscribe(status=>{if(status==="CHANNEL_ERROR"||status==="TIMED_OUT")toast("Canlı mesaj bağlantısı kesildi; sayfayı yenileyin")});
  }
  function renderWorkspace(){
    const active=state.contacts.find(c=>c.id===state.active), msgs=state.messages[state.active]||[];
    $("#app").innerHTML=`<section class="workspace ${active?'chat-open':''}"><aside class="sidebar"><header class="sidebar-head"><div class="brand"><span class="brand-mark">${icon("lock")}</span>BeChat</div><button class="icon-btn" id="settings" aria-label="Ayarlar">${icon("gear")}</button></header><div class="profile"><div class="avatar">${initials(state.profile.display_name)}</div><div class="profile-copy"><strong>${esc(state.profile.display_name)}</strong><span>● ${state.demo?'Demo modu':'Supabase bağlantılı'}</span></div></div><input class="search" id="search" placeholder="Sohbetlerde ara">${state.requests.length?`<div class="section-label request-label">Mesaj istekleri · ${state.requests.length}</div><div class="request-list">${requestList()}</div>`:''}<div class="section-label">Şifreli konuşmalar</div><div class="contact-list">${contactList()}</div><footer class="sidebar-foot"><button class="btn secondary block" id="newChat">${icon("plus")} Yeni güvenli sohbet</button></footer></aside><section class="chat">${active?chatView(active,msgs):emptyView()}</section></section>`;
    bindWorkspace(active);
  }
  function contactList(filter=""){const items=state.contacts.filter(c=>c.display_name.toLowerCase().includes(filter.toLowerCase()));return items.map(c=>{const last=(state.messages[c.id]||[]).at(-1);return `<button class="contact ${state.active===c.id?'active':''}" data-contact="${c.id}"><span class="avatar" style="background:${c.color}">${initials(c.display_name)}</span><span class="contact-main"><span class="contact-line"><strong>${esc(c.display_name)} ${c.verified?'✓':''}</strong><time>${last?nowText(last.created_at):''}</time></span><span class="preview">${last?esc(last.plaintext):esc(c.status)}</span></span></button>`}).join("")||'<div class="empty">Henüz sohbet yok.</div>'}
  function requestList(){return state.requests.map(c=>`<article class="message-request"><div class="request-person"><span class="avatar" style="background:${c.color}">${initials(c.display_name)}</span><span class="profile-copy"><strong>${esc(c.display_name)}</strong><span>${esc(c.email)}</span></span></div><p>${esc((state.messages[c.id]||[]).at(-1)?.plaintext||"Yeni mesaj isteği")}</p><div class="request-actions"><button class="btn ghost" data-reject="${c.id}">Reddet</button><button class="btn" data-accept="${c.id}">Kabul et</button></div></article>`).join("")}
  function emptyView(){return `<div class="empty"><div><span class="brand-mark">${icon("shield")}</span><h2>Güvenli bir sohbet seçin</h2><p>Mesaj içeriği tarayıcınızda şifrelenir.<br>Supabase yalnızca şifreli paketi taşır.</p></div></div>`}
  function chatView(c,msgs){return `<header class="chat-head"><button class="icon-btn back" id="back">${icon("back")}</button><div class="avatar" style="background:${c.color}">${initials(c.display_name)}</div><div class="profile-copy"><strong>${esc(c.display_name)} ${c.verified?'✓':''}</strong><span>${c.verified?'Doğrulanmış E2EE':'Uçtan uca şifreli'}</span></div><div class="head-actions"><button class="icon-btn" id="verify" title="Güvenlik numarası">${icon("shield")}</button><button class="icon-btn settings-hide" id="inspectInfo" title="Bağlantı bilgisi">${icon("info")}</button></div></header><div class="security-strip">${icon("lock")} Mesaj metni cihazınızdan çıkmadan AES-256-GCM ile şifrelenir.</div><div class="messages" id="messages">${msgs.length?msgs.map(messageView).join(""):'<div class="empty">İlk güvenli mesajı siz gönderin.</div>'}</div><div class="composer-wrap"><div class="typing" id="typing"></div><form class="composer" id="composer"><textarea id="messageInput" rows="1" placeholder="Uçtan uca şifreli mesaj…" required></textarea><button class="btn send" aria-label="Gönder">${icon("send")}</button></form></div>`}
  function messageView(m){return `<article class="message ${m.mine?'mine':''}" data-message="${m.id}"><p>${esc(m.plaintext)}</p><div class="message-meta">${m.expires_at?'⏱ ':''}${nowText(m.created_at)} ${m.mine?`<span class="ticks">${m.status==='read'?'✓✓':m.status==='delivered'?'✓✓':'✓'}</span>`:''}</div></article>`}
  function bindWorkspace(active){
    document.querySelectorAll("[data-contact]").forEach(x=>x.onclick=()=>{state.active=x.dataset.contact;render();setTimeout(()=>{$("#messages")?.scrollTo(0,999999)},0)});
    document.querySelectorAll("[data-accept]").forEach(x=>x.onclick=()=>acceptRequest(x.dataset.accept));document.querySelectorAll("[data-reject]").forEach(x=>x.onclick=()=>rejectRequest(x.dataset.reject));
    $("#search")?.addEventListener("input",e=>$(".contact-list").innerHTML=contactList(e.target.value));
    $("#back")?.addEventListener("click",()=>{state.active=null;render()});$("#newChat")?.addEventListener("click",newChatModal);$("#settings")?.addEventListener("click",settingsModal);$("#verify")?.addEventListener("click",()=>verifyModal(active));$("#inspectInfo")?.addEventListener("click",()=>connectionModal(active));
    $("#composer")?.addEventListener("submit",e=>{e.preventDefault();sendMessage(active,$("#messageInput").value)});
    $("#messageInput")?.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();if(e.currentTarget.value.trim())$("#composer").requestSubmit()}});
    document.querySelectorAll("[data-message]").forEach(x=>x.onclick=()=>inspectModal((state.messages[state.active]||[]).find(m=>m.id===x.dataset.message)));
  }
  async function acceptRequest(id){const c=state.requests.find(x=>x.id===id);if(!c)return;if(!state.demo){const {error}=await state.client.from("contacts").upsert({owner_id:state.profile.id,contact_id:id});if(error)return toast("İstek kabul edilemedi: "+error.message)}state.requests=state.requests.filter(x=>x.id!==id);if(!state.contacts.some(x=>x.id===id))state.contacts.unshift(c);state.active=id;render();toast(`${c.display_name} kişilere eklendi`)}
  async function rejectRequest(id){const c=state.requests.find(x=>x.id===id);if(!c)return;if(!state.demo){const {error}=await state.client.from("blocked_users").upsert({owner_id:state.profile.id,blocked_id:id});if(error)return toast("İstek reddedilemedi: "+error.message)}state.requests=state.requests.filter(x=>x.id!==id);state.blocked.push(id);delete state.messages[id];render();toast(`${c.display_name} engellendi`)}
  async function sendMessage(contact,text){if(!text.trim())return;try{if(state.demo){const raw=enc.encode(text),digest=await crypto.subtle.digest("SHA-256",raw);const m={id:uid(),plaintext:text.trim(),mine:true,created_at:Date.now(),status:"sent",ciphertext:b64(raw),iv:b64(crypto.getRandomValues(new Uint8Array(12))),digest:b64(digest)};(state.messages[contact.id]??=[]).push(m);render();setTimeout(()=>{m.status="delivered";render()},450);setTimeout(()=>demoReply(contact),1300)}else{const payload=await encryptMessage(text.trim(),contact);const {data,error}=await state.client.from("messages").insert({...payload,sender_id:state.profile.id,recipient_id:contact.id}).select().single();if(error)throw error;data.mine=true;data.plaintext=text.trim();(state.messages[contact.id]??=[]).push(data);render()}}catch(err){toast("Mesaj gönderilemedi: "+err.message)} }
  function demoReply(contact){const replies=["Mesajını aldım — bu cihazda çözüldü. 🔒","Güvenlik numarası bende de eşleşiyor.","Harika, şifreli kanal çalışıyor."];const m={id:uid(),plaintext:replies[Math.floor(Math.random()*replies.length)],mine:false,created_at:Date.now(),status:"read",ciphertext:"ZW5jcnlwdGVkLXBlZXItcmVwbHk=",iv:"c2VjdXJlLW5vbmNl",digest:"2cf24dba5fb0a30e26e83b2ac5b9e29e"};(state.messages[contact.id]??=[]).push(m);render()}
  function modal(html){document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" id="modal"><div class="modal">${html}</div></div>`);$("#modal").onclick=e=>{if(e.target.id==="modal"||e.target.closest("[data-close]"))$("#modal").remove()}}
  async function newChatModal(){
    modal(`<h2>Kayıtlı kullanıcılar</h2><p>Mesajlaşmak istediğiniz kişiyi listeden seçin.</p><input class="search user-search" id="userSearch" placeholder="İsim veya e-postada ara"><div class="user-directory" id="userDirectory"><div class="empty">Kullanıcılar yükleniyor…</div></div><div class="modal-actions"><button class="btn ghost" data-close>Kapat</button></div>`);
    let users;
    if(state.demo)users=seedContacts;
    else{const {data,error}=await state.client.from("profiles").select("id,email,display_name,status,public_key").neq("id",state.profile.id).order("display_name");if(error){$("#userDirectory").innerHTML='<div class="empty">Kullanıcı listesi yüklenemedi.</div>';return toast(error.message)}users=data||[]}
    const draw=(query="")=>{const q=query.toLocaleLowerCase("tr-TR"),shown=users.filter(u=>!state.blocked.includes(u.id)&&`${u.display_name} ${u.email}`.toLocaleLowerCase("tr-TR").includes(q));$("#userDirectory").innerHTML=shown.map(u=>`<button class="directory-user" data-user="${u.id}"><span class="avatar" style="background:hsl(${Math.abs(hash(u.id))%360} 60% 48%)">${initials(u.display_name)}</span><span class="profile-copy"><strong>${esc(u.display_name)}</strong><span>${esc(u.email)}</span></span><span class="directory-action">Ekle</span></button>`).join("")||'<div class="empty">Eşleşen kullanıcı bulunamadı.</div>';document.querySelectorAll("[data-user]").forEach(btn=>btn.onclick=async()=>{const user=users.find(x=>x.id===btn.dataset.user),existing=state.contacts.find(x=>x.id===user.id);if(!state.demo&&!existing){const {error}=await state.client.from("contacts").upsert({owner_id:state.profile.id,contact_id:user.id});if(error)return toast("Kişi eklenemedi: "+error.message)}if(!existing)state.contacts.unshift(decorateContact(user));state.requests=state.requests.filter(x=>x.id!==user.id);$("#modal").remove();state.active=user.id;render()})};
    draw();$("#userSearch").oninput=e=>draw(e.target.value);
  }
  function verifyModal(c){let digits=String(Math.abs(hash(state.profile.id+c.id))).padEnd(60,"7").repeat(5).slice(0,60).match(/.{1,5}/g).join(" ");modal(`<span class="status-pill">${icon("shield")} Güvenlik kontrolü</span><h2>${esc(c.display_name)} ile doğrulayın</h2><p>Bu 60 haneli numarayı diğer cihazdaki numarayla sesli veya yüz yüze karşılaştırın.</p><div class="crypto-box"><label>GÜVENLİK NUMARASI</label><code>${digits}</code></div><div class="modal-actions"><button class="btn ghost" data-close>Kapat</button><button class="btn" id="toggleVerify">${c.verified?'Doğrulamayı kaldır':'Doğrulandı olarak işaretle'}</button></div>`);$("#toggleVerify").onclick=async()=>{c.verified=!c.verified;if(!state.demo)await state.client.from("contacts").update({verified:c.verified}).eq("owner_id",state.profile.id).eq("contact_id",c.id);$("#modal").remove();render();toast(c.verified?"Kişi doğrulandı":"Doğrulama kaldırıldı")}}
  function inspectModal(m){modal(`<span class="status-pill">${icon("lock")} Kripto inceleyici</span><h2>Şifreli paket ayrıntıları</h2><p>Açık metin yalnızca bu cihazda gösterilir. Buluta giden alanlar aşağıdadır.</p><div class="crypto-grid"><div class="crypto-box"><label>AES-256-GCM CIPHERTEXT</label><code>${esc(m.ciphertext)}</code></div><div class="crypto-box"><label>96-BIT IV / NONCE</label><code>${esc(m.iv)}</code></div><div class="crypto-box"><label>SHA-256 ÖZETİ</label><code>${esc(m.digest)}</code></div><div class="crypto-box"><label>İLETİM DURUMU</label><code>${esc(m.status.toUpperCase())} · ${new Date(m.created_at).toLocaleString("tr-TR")}</code></div></div><div class="modal-actions"><button class="btn" data-close>Tamam</button></div>`)}
  function connectionModal(c){modal(`<span class="status-pill">${icon("shield")} E2EE aktif</span><h2>Bağlantı mimarisi</h2><p>Tarayıcılar P-256 ECDH ile ortak sır üretir. Mesaj AES-256-GCM ile yerelde şifrelenir; Supabase yalnızca ciphertext, IV ve teslim durumunu saklar.</p><div class="crypto-box"><label>KARŞI TARAF AÇIK ANAHTARI</label><code>${esc(c.public_key).slice(0,180)}</code></div><div class="modal-actions"><button class="btn" data-close>Anladım</button></div>`)}
  function settingsModal(){modal(`<h2>Güvenlik ve gizlilik</h2><p><b>${esc(state.profile.display_name)}</b><br>${esc(state.profile.email)}</p><div class="crypto-grid"><div class="crypto-box"><label>VERİ BAĞLANTISI</label><code>${state.demo?'Yerel demo — sunucuya veri gönderilmiyor':'Supabase Auth + Postgres + Realtime'}</code></div><div class="crypto-box"><label>ÖZEL ANAHTAR</label><code>Yalnızca bu tarayıcının yerel deposunda tutulur.</code></div></div><div class="modal-actions"><button class="btn ghost" data-close>Kapat</button><button class="btn danger" id="logout">Oturumu kapat</button></div>`);$("#logout").onclick=async()=>{if(!state.demo)await state.client.auth.signOut();state.session=null;state.demo=false;state.step="email";state.active=null;$("#modal").remove();render()}}
  async function init(){if(state.client){const {data}=await state.client.auth.getSession();if(data.session){state.session=data.session;await bootstrapReal();return}}render()}
  init();
})();
