/* Curated alpha catalog. No external movie API or current popularity claims. */
window.TILKI_CATALOG = [
  {id:'interstellar',title:'Interstellar',year:2014,type:'film',genres:['Bilim Kurgu','Drama'],symbol:'✦',color:'#31527d',tag:'UZAYIN ÖTESİNDE',description:'Dünya yaşanabilirliğini kaybederken bir grup astronot, insanlık için yeni bir yuva aramak üzere yıldızlararası bir yolculuğa çıkar.'},
  {id:'breaking-bad',title:'Breaking Bad',year:2008,type:'series',genres:['Drama','Gerilim'],symbol:'Br',color:'#315947',tag:'HER SEÇİMİN BİR BEDELİ VAR',description:'Bir kimya öğretmeninin aldığı teşhis, onu ve eski öğrencisini suç dünyasının içine sürükler.'},
  {id:'the-dark-knight',title:'The Dark Knight',year:2008,type:'film',genres:['Aksiyon','Gerilim'],symbol:'◈',color:'#37435f',tag:'GOTHAM KARANLIĞA BÜRÜNÜR',description:'Batman, Gotham’ın düzenini kaosa dönüştürmeye kararlı Joker ile karşı karşıya gelir.'},
  {id:'dune-part-two',title:'Dune: Part Two',year:2024,type:'film',genres:['Bilim Kurgu','Aksiyon'],symbol:'◒',color:'#9c683e',tag:'KADERİNİ SEÇ',description:'Paul Atreides, Chani ve Fremenlerle birlikte çöl gezegeninde hem intikamın hem de kaderinin peşine düşer.'},
  {id:'stranger-things',title:'Stranger Things',year:2016,type:'series',genres:['Bilim Kurgu','Gerilim'],symbol:'Ⅺ',color:'#79384a',tag:'BAŞKA BİR DÜNYA',description:'Küçük bir kasabada bir çocuğun kaybolması, arkadaşlarını gizli deneylerin ve doğaüstü olayların merkezine taşır.'},
  {id:'inception',title:'Inception',year:2010,type:'film',genres:['Bilim Kurgu','Gerilim'],symbol:'◎',color:'#436777',tag:'BİR FİKİR HER ŞEYİ DEĞİŞTİRİR',description:'Rüyalara girerek sır çalan bir uzman, bu kez bir fikri zihne yerleştirmek için tehlikeli bir görevi kabul eder.'},
  {id:'peaky-blinders',title:'Peaky Blinders',year:2013,type:'series',genres:['Drama','Gerilim'],symbol:'♠',color:'#655644',tag:'BIRMINGHAM, 1919',description:'Shelby ailesi, savaş sonrası Birmingham sokaklarından başlayarak gücünü genişletmeye çalışır.'},
  {id:'whiplash',title:'Whiplash',year:2014,type:'film',genres:['Drama','Müzik'],symbol:'◉',color:'#88703d',tag:'RİTMİN SINIRI YOK',description:'Genç bir caz davulcusu, sınırlarını zorlayan bir eğitmenin yönetiminde başarı arzusuyla yüzleşir.'},
  {id:'the-grand-budapest-hotel',title:'The Grand Budapest Hotel',year:2014,type:'film',genres:['Komedi','Drama'],symbol:'◇',color:'#8b576b',tag:'BİR OTEL DOLUSU HİKÂYE',description:'Bir otelin efsanevi görevlisi ve genç yardımcısı, çalınan bir tablo etrafında gelişen maceraya atılır.'},
  {id:'dark',title:'Dark',year:2017,type:'series',genres:['Bilim Kurgu','Gerilim'],symbol:'∞',color:'#426257',tag:'BAŞLANGIÇ SONDUR',description:'Kaybolan çocuklar, bir Alman kasabasındaki aileleri kuşaklar boyunca birbirine bağlayan zaman sırlarını ortaya çıkarır.'},
  {id:'la-la-land',title:'La La Land',year:2016,type:'film',genres:['Müzik','Drama'],symbol:'♫',color:'#665798',tag:'HAYAL ETMEYE DEVAM',description:'Los Angeles’ta yolları kesişen bir oyuncu ve caz müzisyeni, aşklarıyla hayallerini birlikte sürdürmeye çalışır.'},
  {id:'the-bear',title:'The Bear',year:2022,type:'series',genres:['Drama','Komedi'],symbol:'✳',color:'#4f657c',tag:'HER SANİYE ÖNEMLİ',description:'Genç bir şef, aile sandviç dükkânını devralmak için Chicago’ya döner; mutfaktaki değişim herkesin hayatına dokunur.'}
];
