const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
function setup(){
  const nodes=new Map();
  const element=()=>({value:'',dataset:{},innerHTML:'',classList:{add(){},remove(){}},addEventListener(){},focus(){},setSelectionRange(){},remove(){}});
  for(const id of ['#app','#toast','#search','#settings','.contact-list','#authForm','#messageInput'])nodes.set(id,element());
  nodes.set('#socialPane',{hidden:true});
  const document={hidden:false,activeElement:null,querySelector:s=>nodes.get(s)||null,querySelectorAll:()=>[],addEventListener(){},body:{insertAdjacentHTML(){nodes.set('#modal',element());nodes.set('.modal',element());}}};
  const window={dispatchEvent(){},addEventListener(){},TilkiCinema:{go(){}}};
  const context={document,window,Event,crypto:globalThis.crypto,Date,URL,location:{origin:'https://test.local',pathname:'/'},setTimeout:()=>0,clearTimeout,console};
  vm.createContext(context);vm.runInContext(fs.readFileSync('catalog.js','utf8'),context);
  const code=fs.readFileSync('app.js','utf8').replace('  init().catch','  window.testing={state,normalizeContent,mergeMessage,transmit,bootstrap,authenticate,clearSession,render,messageView,initials};\n  init().catch');
  vm.runInContext(code,context);return {...window.testing,nodes,window};
}
function signed(x){Object.assign(x.state,{profile:{id:'me',display_name:'Deniz'},active:'peer',contacts:[{id:'peer',display_name:'Aylin'}]});x.nodes.get('#messageInput').dataset.contact='peer';x.nodes.get('#messageInput').dataset.owner='me';}
test('login page has ordinary signup and password reset without device keys',()=>{const x=setup(),html=x.nodes.get('#app').innerHTML;assert.match(html,/Parolamı unuttum/);assert.match(html,/Kayıt ol/);assert.doesNotMatch(html,/AES|ECDH|anahtar|şifrelen/);});
test('text is escaped and unsupported image schemes are rejected',()=>{const x=setup();signed(x);assert.match(x.messageView({sender_id:'peer',content:{type:'text',text:'<script>alert(1)</script>'},created_at:new Date().toISOString()}),/&lt;script&gt;/);assert.equal(x.normalizeContent({type:'image',data:'javascript:alert(1)'}).type,'legacy');});
test('realtime duplicates merge and read receipts cannot regress',()=>{const x=setup();signed(x);const m={id:'one',sender_id:'peer',recipient_id:'me',content:{type:'text',text:'hey'},created_at:'2026-01-01T00:00:00Z',status:'read'};x.mergeMessage(m);x.mergeMessage({...m,status:'sent'});assert.equal(x.state.messages.peer.length,1);assert.equal(x.state.messages.peer[0].status,'read');x.mergeMessage({...m,id:'other',recipient_id:'someone'});assert.equal(x.state.messages.peer.length,1);});
test('send writes plain content, preserving drafts on failure and retrying same id',async()=>{const x=setup();signed(x);x.nodes.get('#messageInput').value='Merhaba';const sent=[];let fail=true;x.state.client={from(){return{insert(payload){sent.push(payload);return{select(){return{single:async()=>fail?{error:{message:'offline'}}:{data:{...payload,status:'sent',created_at:new Date().toISOString()}}}}}}}}};assert.equal(await x.transmit({type:'text',text:'Merhaba'}),false);assert.equal(x.nodes.get('#messageInput').value,'Merhaba');fail=false;assert.equal(await x.transmit({type:'text',text:'Merhaba'}),true);assert.equal(sent[0].id,sent[1].id);assert.equal(sent[1].content.text,'Merhaba');assert.ok(!('ciphertext' in sent[1]));assert.equal(x.nodes.get('#messageInput').value,'');});
test('signout during send prevents old account data returning',async()=>{const x=setup();signed(x);let finish;x.state.client={from(){return{insert(payload){return{select(){return{single:()=>new Promise(resolve=>{finish=()=>resolve({data:{...payload,status:'sent',created_at:new Date().toISOString()}})})}}}}}}};const pending=x.transmit({type:'text',text:'hey'});x.clearSession();finish();assert.equal(await pending,false);assert.equal(x.state.profile,null);assert.equal(Object.keys(x.state.messages).length,0);});
test('new session bootstraps profile without touching local storage',async()=>{const x=setup();let profileSelect;const channel={on(){return this},subscribe(){return this},unsubscribe(){}};x.state.client={channel:()=>channel,from(table){const query={select(columns){if(table==='profiles')profileSelect=columns;return this},eq(){return this},or(){return this},order(){return this},limit(){return this},maybeSingle:async()=>({data:{id:'new-device',display_name:'Test',status:''}}),then(resolve){return Promise.resolve({data:[]}).then(resolve)}};return query}};await x.bootstrap({user:{id:'new-device',email:'a@example.com'}});assert.equal(x.state.profile.id,'new-device');assert.doesNotMatch(profileSelect,/key/);});
test('password reset requests a return URL and never creates a message',async()=>{const x=setup();x.state.mode='reset';x.nodes.set('#email',{value:'test@example.com'});let args;x.state.client={auth:{resetPasswordForEmail:async(...a)=>{args=a;return{}}}};await x.authenticate({preventDefault(){},submitter:{}});assert.equal(args[0],'test@example.com');assert.equal(args[1].redirectTo,'https://test.local/#auth');assert.match(x.state.notice,/yenileme bağlantısı/);});
test('signup mismatch is rejected before contacting Supabase',async()=>{const x=setup();x.state.mode='signup';x.nodes.set('#password',{value:'password123'});x.nodes.set('#passwordAgain',{value:'other123'});let called=false;x.state.client={auth:{signUp(){called=true}}};await x.authenticate({preventDefault(){},submitter:{}});assert.equal(called,false);assert.match(x.state.notice,/eşleşmiyor/);});
